config/routes.rb
Rails.application.routes.draw do

  resources :users,:user

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def new
	end

	def create
		User.create(name: params[:name], age: params[:age], address: params[:address], hobby: params[:hobby], birth: params[:birth])
        
	end

	def show
        @tell = params[:tell]
        @wheigh = params[:wheigh]
	end

	def edit
	end

	def update
	end

	def destroy
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fukui</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

  <body>

    <p>ナビゲーションバー：</p>
    <%= link_to 'index', users_path %>
    <%= link_to 'new', new_user_path %>
    <%= link_to 'show', 'users/show' %>
   

    <div class="contents">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/create.html.erb
<h3>登録しました</h3>
<%= @name %>
<%= @age %>
<%= @address %>
<%= @hobby %>
<%= @birth %>

app/views/users/destroy.html.erb
<% @hello = "1aaaaaaaaaa" %>
<%= @hello %>

app/views/users/edit.html.erb
<% @hello = "hello world" %>
<%= @hello %>

app/views/users/index.html.erb
<% @users.each do |user| %>

<%= user.name %>
<%= user.age %>
<%= user.address %>
<%= user.hobby %>
<%= user.birth %>

<% end %>

app/views/users/new.html.erb
<%= form_tag(users_path, method: :post) do %>
  <%# ↑ターミナルで確認できる　users の　POSTメソッド　なのでuserコントローラーのcreateアクション が動く%>
  <%# postメソッドでは、users_controllerのcreateメソッドが動く
  なので、createアクションのviewが動いてcreate.html.erbが表示される %>
  <table>
    <tr>
     <th><%= label_tag :名前 %></th>
     <th><%= text_field_tag :name %></th>
    </tr>
    <tr>
     <th><%= label_tag :年齢 %></th>
     <th><%= text_field_tag :age %></th>
    </tr>
    <tr>
     <th><%= label_tag :住所 %></th>
     <th><%= text_field_tag :address %></th>
    </tr>
    <tr>
     <th><%= label_tag :趣味 %></th>
     <th><%= text_field_tag :hobby %></th>
    </tr>
    <tr>
     <th><%= label_tag :生年月日 %></th>
     <th><%= text_field_tag :birth %></th>
    </tr>
    <tr>
     <th></th>
     <th><%= submit_tag "登録" %></th>
    </tr>
  </table>
<% end %>

<%= form_tag(user_index_path, method: :get) do %>
          <%# ↑ターミナルで確認できる　users の　POSTメソッド　なのでuserコントローラーのcreateアクション が動く%>

 <%# postメソッドでは、users_controllerのcreateメソッドが動く
     なので、createアクションのviewが動いてcreate.html.erbが表示される %>
  <div>
    <%= label_tag :tell %>
    <%= text_field_tag :電話番号 %>
  </div>
  <div>
  <%= label_tag :wheigh %>
  <%= text_field_tag :体重 %>
  </div>


  <%= submit_tag "登録" %>
<% end %>

app/views/users/show.html.erb
<h3>登録しました</h3>
<%= @tell %>
<%= @wheigh %>

app/views/users/update.html.erb
<% @hello = "hello world" %>
<%= @hello %>